name: Windows released package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/validate-release.yml
    with:
      runner: windows-2022
      archive_suffix: windows-x64-msvc143-md
      archive_extension: zip
